### ISSUE TITLE
small city lists?

### ISSUE THREAD

**Issue by samlecuyer** [DarrenN/calligraphus#5]
LA has a [weird shape](http://la.cateches.is/#/2) and envelopes other cities in such a way that results in a lot of our meetups technically not happening within city limits.  So on paperswelove.org, last night's was listed as Marina Del Rey, last month was Santa Monica, etc.

Can we maybe keep a list of neighboring cities that our chapter might visit so that it always shows up as Los Angeles rather than wherever it technically is?

**Comment by DarrenN** [comment]
So, Meetup.com uses Geolocation on the address of your meetup to provide the city name which is why it keeps moving around on you. We could probably do something like associate your [Meetup ID](https://github.com/papers-we-love/papers-we-love.github.io/blob/00a4ed9a4e13594bd1407254a70e9b37a3792724/data/meetup/chapters.yml#L6246) with a city name (Los Angeles).

This might happen over in the [site repo itself](https://github.com/papers-we-love/papers-we-love.github.io), as a lot of data massaging and transmogrifying happens there as well.

Lemme ruminate on it.

**Comment by samlecuyer** [comment]
@DarrenN rumination sounds good. If this is a hassle, then forget it.  I just noticed it and I thought I'd bring it up.  LA's geography is a little different from NYC's.
